<?php

namespace Database\Seeders;

use App\Models\Devotional;
use App\Models\DevotionalCategory;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class LifeEventSpiritualContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $author = User::updateOrCreate(
            ['email' => 'super@admin.com'],
            [
                'name' => 'MannaRise Super Admin',
                'password' => '9638',
                'is_admin' => true,
                'is_super_admin' => true,
            ],
        );

        $categories = collect([
            'New Seasons' => 'Spiritual direction for fresh starts, relocation, graduation, transitions, and rebuilding.',
            'Grief and Comfort' => 'Biblical comfort for loss, disappointment, sorrow, and seasons of mourning.',
            'Peace and Anxiety' => 'Guidance for fear, pressure, mental heaviness, and learning rest in God.',
            'Relationships' => 'Wisdom for love, friendship, conflict, marriage, singleness, and reconciliation.',
            'Family and Home' => 'Devotionals for parenting, family pressure, home life, and generational blessing.',
            'Work and Calling' => 'Spiritual formation for career, business, leadership, service, and purpose.',
            'Money and Stewardship' => 'Faithful wisdom for finances, generosity, debt, lack, and provision.',
            'Health and Healing' => 'Hope for sickness, recovery, weakness, caregiving, and embodied faith.',
            'Waiting and Discernment' => 'Help for delayed answers, decision making, and trusting God over time.',
            'Failure and Restoration' => 'Grace for sin, failure, regret, repentance, and new obedience.',
            'Spiritual Growth' => 'Practices that deepen prayer, Scripture, holiness, worship, and daily surrender.',
            'Courage and Resilience' => 'Strength for persecution, pressure, loneliness, change, and perseverance.',
        ])->mapWithKeys(function (string $description, string $name) {
            $category = DevotionalCategory::updateOrCreate(
                ['slug' => Str::slug($name)],
                [
                    'name' => $name,
                    'slug' => Str::slug($name),
                    'description' => $description,
                    'is_active' => true,
                ],
            );

            return [$name => $category];
        });

        $posts = $this->posts();

        foreach ($posts as $index => $post) {
            Devotional::updateOrCreate(
                ['slug' => Str::slug($post['title'])],
                [
                    'devotional_category_id' => $categories[$post['category']]->id,
                    'user_id' => $author->id,
                    'title' => $post['title'],
                    'slug' => Str::slug($post['title']),
                    'bible_reference' => $post['reference'],
                    'bible_text' => $post['verse'],
                    'content' => $this->buildContent($post),
                    'reflection_question' => $post['reflection'],
                    'prayer_point' => $post['prayer'],
                    'declaration' => $post['declaration'],
                    'published_at' => now()->subDays(count($posts) - $index),
                    'is_featured' => $index < 3,
                    'is_published' => true,
                    'reading_time' => 8,
                ],
            );
        }
    }

    /**
     * @return array<int, array<string, string>>
     */
    private function posts(): array
    {
        return [
            [
                'category' => 'New Seasons',
                'title' => 'When God Opens a New Chapter',
                'reference' => 'Isaiah 43:19',
                'verse' => 'Behold, I will do a new thing; now it shall spring forth; shall ye not know it?',
                'event' => 'starting over, entering a new season, relocating, graduating, changing direction, or rebuilding after disruption',
                'truth' => 'God is not confused by transition. He sees the road before you, the fear inside you, and the grace required for every step.',
                'practice' => 'Begin the new season with consecration. Before making many announcements, make a quiet altar. Ask God what must come with you, what must be left behind, and what habits must be planted early.',
                'discipline' => 'Write three commitments for this season: one spiritual rhythm, one relationship to protect, and one obedience you will not delay.',
                'warning' => 'Do not treat a new season as permission to become careless. Fresh opportunities still need prayer, humility, patience, and wise counsel.',
                'hope' => 'The God who begins a work also sustains it. You are not walking into emptiness; you are walking into prepared grace.',
                'reflection' => 'What is God asking me to carry forward, and what is He asking me to release?',
                'prayer' => 'Lord, order my steps in this new chapter and make my heart sensitive to Your direction.',
                'declaration' => 'I enter new seasons with faith, humility, and obedience.',
            ],
            [
                'category' => 'New Seasons',
                'title' => 'Starting Again Without Shame',
                'reference' => 'Lamentations 3:22-23',
                'verse' => 'It is of the LORDS mercies that we are not consumed, because his compassions fail not. They are new every morning.',
                'event' => 'rebuilding after a mistake, divorce, job loss, failed plan, public embarrassment, or private regret',
                'truth' => 'Starting again is not proof that your life is over. Sometimes it is the evidence that mercy has interrupted what shame wanted to finish.',
                'practice' => 'Let repentance be honest, but do not let shame become your identity. Confess what must be confessed, repair what can be repaired, and receive the mercy God freely gives.',
                'discipline' => 'Choose one small act of obedience today that agrees with grace instead of condemnation.',
                'warning' => 'Do not punish yourself longer than God has called you to repent. False humility keeps staring at failure after God has invited you to rise.',
                'hope' => 'Mercy does not erase wisdom; it gives you power to walk wiser. Your next step can be cleaner, slower, deeper, and more surrendered.',
                'reflection' => 'Where have I confused repentance with self-punishment?',
                'prayer' => 'Father, teach me to receive mercy and rebuild with a clean heart.',
                'declaration' => 'The mercy of God gives me courage to begin again.',
            ],
            [
                'category' => 'Grief and Comfort',
                'title' => 'When Loss Changes the Shape of Life',
                'reference' => 'Psalm 34:18',
                'verse' => 'The LORD is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit.',
                'event' => 'bereavement, heartbreak, miscarriage, friendship loss, family separation, or any sorrow that makes life feel unfamiliar',
                'truth' => 'Grief is not a lack of faith. It is love learning how to breathe in a world that has changed. God does not stand far away from broken hearts; He draws near.',
                'practice' => 'Bring your grief into prayer without editing it. Tell God what you miss, what you fear, what you do not understand, and what feels too heavy to carry.',
                'discipline' => 'Create a simple rhythm of remembrance and hope: light a quiet moment, read one Psalm, speak one thanksgiving, and ask for strength for one day only.',
                'warning' => 'Do not rush yourself because other people are uncomfortable with pain. Healing is not a performance for the impatient.',
                'hope' => 'The presence of God does not always remove tears immediately, but it keeps tears from becoming your whole future.',
                'reflection' => 'What part of my grief have I been afraid to bring honestly to God?',
                'prayer' => 'God of comfort, meet me in sorrow and carry what my heart cannot carry alone.',
                'declaration' => 'The Lord is near to my broken heart.',
            ],
            [
                'category' => 'Grief and Comfort',
                'title' => 'Comfort for the Day You Cannot Explain',
                'reference' => '2 Corinthians 1:3-4',
                'verse' => 'Blessed be God, even the Father of our Lord Jesus Christ, the Father of mercies, and the God of all comfort.',
                'event' => 'confusing pain, unanswered questions, sudden trouble, or a season where explanations feel too small',
                'truth' => 'There are days when the soul does not need a speech; it needs presence. God gives comfort that is deeper than explanation.',
                'practice' => 'Receive comfort as a spiritual discipline. Sit before God without trying to solve every question. Let Scripture be a blanket before it becomes a map.',
                'discipline' => 'Choose one verse of comfort and repeat it slowly throughout the day, not as a slogan but as a place to rest.',
                'warning' => 'Do not demand that your mind fully understand before your heart is allowed to be held by God.',
                'hope' => 'The Father of mercies knows how to reach places in you that words cannot touch.',
                'reflection' => 'Where do I need the comfort of God more than I need an explanation?',
                'prayer' => 'Father of mercies, quiet my soul and teach me to rest in Your nearness.',
                'declaration' => 'God comforts me with mercy that is stronger than confusion.',
            ],
            [
                'category' => 'Peace and Anxiety',
                'title' => 'Peace When Your Mind Will Not Slow Down',
                'reference' => 'Philippians 4:6-7',
                'verse' => 'Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.',
                'event' => 'anxiety, overthinking, pressure, uncertainty, panic, or nights when the mind keeps rehearsing fear',
                'truth' => 'Peace is not the denial of responsibility. Peace is the presence of God guarding the inner life while you do what wisdom requires.',
                'practice' => 'Turn anxious loops into specific prayers. Name the concern, ask for help, thank God for one evidence of His care, and take the next wise action.',
                'discipline' => 'Make a worry list and a prayer list. For every fear written down, write one request and one act of trust.',
                'warning' => 'Do not let anxiety become your counselor. Fear can shout, but it cannot shepherd your future.',
                'hope' => 'The peace of God can guard your heart before all circumstances are resolved.',
                'reflection' => 'What concern needs to become a prayer instead of a private storm?',
                'prayer' => 'Lord, guard my heart and mind with Your peace as I surrender my concerns to You.',
                'declaration' => 'Gods peace is stronger than the noise in my mind.',
            ],
            [
                'category' => 'Peace and Anxiety',
                'title' => 'Rest for the Weary Soul',
                'reference' => 'Matthew 11:28',
                'verse' => 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.',
                'event' => 'burnout, exhaustion, ministry fatigue, work pressure, caregiving, or spiritual dryness',
                'truth' => 'Jesus does not invite the weary to prove they are strong. He invites them to come. Rest begins when you stop pretending you are not tired.',
                'practice' => 'Come to Christ with your real weight. Tell Him what has become heavy, where you feel depleted, and what burden you picked up without His instruction.',
                'discipline' => 'Practice one holy pause today: no phone, no performance, no rushing. Sit quietly, breathe, and pray, "Jesus, I come."',
                'warning' => 'Do not confuse constant motion with faithfulness. A soul that never rests eventually serves from emptiness.',
                'hope' => 'The rest Jesus gives does not make you careless; it makes you whole enough to obey with joy.',
                'reflection' => 'What burden am I carrying that Jesus did not ask me to carry alone?',
                'prayer' => 'Jesus, I come to You with my weariness. Teach me Your rest.',
                'declaration' => 'I receive the rest of Christ for my soul.',
            ],
            [
                'category' => 'Relationships',
                'title' => 'Loving Without Losing Yourself',
                'reference' => '1 Corinthians 13:4',
                'verse' => 'Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up.',
                'event' => 'friendship, dating, marriage, family pressure, people pleasing, or relationships that need both love and wisdom',
                'truth' => 'Biblical love is not weakness. It is patient, truthful, kind, holy, and wise. Love serves others without surrendering obedience to God.',
                'practice' => 'Ask God to purify both your affection and your boundaries. Love should make you more faithful, not more afraid.',
                'discipline' => 'Name one relationship where you need to practice honest kindness: speak truth without cruelty, and show care without control.',
                'warning' => 'Do not call fear love. Do not call control protection. Do not call silence peace if truth is being avoided.',
                'hope' => 'God can teach you a love that is tender enough to serve and strong enough to obey.',
                'reflection' => 'Where do I need healthier love, clearer truth, or wiser boundaries?',
                'prayer' => 'Lord, teach me to love with patience, purity, courage, and wisdom.',
                'declaration' => 'The love of God forms the way I relate to others.',
            ],
            [
                'category' => 'Relationships',
                'title' => 'When You Need to Forgive',
                'reference' => 'Ephesians 4:32',
                'verse' => 'And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christs sake hath forgiven you.',
                'event' => 'offense, betrayal, family conflict, church hurt, workplace tension, or repeated memories of harm',
                'truth' => 'Forgiveness is not pretending the wound did not matter. Forgiveness is releasing vengeance to God while you pursue healing, truth, and wise boundaries.',
                'practice' => 'Begin with honesty. Tell God what happened, what it cost you, and what you are afraid forgiveness will mean.',
                'discipline' => 'Pray a release prayer daily for seven days: "Lord, I release revenge to You. Lead me in truth and healing."',
                'warning' => 'Do not confuse forgiveness with immediate trust. Trust is rebuilt through repentance, time, fruit, and wisdom.',
                'hope' => 'The grace that forgave you can also free you from living chained to the offense.',
                'reflection' => 'What does obedience in forgiveness look like without denying wisdom or truth?',
                'prayer' => 'Father, help me forgive as one who has been forgiven, and lead me in wise healing.',
                'declaration' => 'I release vengeance to God and receive freedom in Christ.',
            ],
            [
                'category' => 'Family and Home',
                'title' => 'Building a Home Filled With Peace',
                'reference' => 'Joshua 24:15',
                'verse' => 'As for me and my house, we will serve the LORD.',
                'event' => 'family life, parenting, marriage, shared housing, family conflict, or creating a spiritually healthy home',
                'truth' => 'A peaceful home is not built by decoration alone. It is built by worship, repentance, honor, order, and the daily choice to serve the Lord.',
                'practice' => 'Invite God into ordinary family rhythms: meals, conversations, correction, forgiveness, budgeting, rest, and decisions.',
                'discipline' => 'Choose one household practice to begin this week: shared prayer, Scripture at breakfast, weekly gratitude, or a conflict repair conversation.',
                'warning' => 'Do not demand a peaceful home while feeding it with harsh words, secrecy, prayerlessness, or unresolved offense.',
                'hope' => 'God can make your home a place where hearts are formed, burdens are shared, and His presence is honored.',
                'reflection' => 'What atmosphere am I helping create in my home?',
                'prayer' => 'Lord, make my home a place of peace, truth, prayer, and love.',
                'declaration' => 'My household will be shaped by the presence and wisdom of God.',
            ],
            [
                'category' => 'Family and Home',
                'title' => 'Grace for Parenting and Caregiving',
                'reference' => 'Isaiah 40:11',
                'verse' => 'He shall feed his flock like a shepherd: he shall gather the lambs with his arm, and carry them in his bosom.',
                'event' => 'raising children, caring for aging parents, mentoring, carrying family responsibilities, or feeling stretched by care',
                'truth' => 'Caregiving is holy work, but it is not work you can sustain without grace. The Shepherd cares for you while you care for others.',
                'practice' => 'Let God shepherd your tone, your patience, your correction, your exhaustion, and your expectations.',
                'discipline' => 'Before responding to a difficult need today, pause and pray, "Shepherd my heart before I shepherd this moment."',
                'warning' => 'Do not let responsibility turn into resentment. Bring your limits to God before they harden into anger.',
                'hope' => 'The Lord sees unseen labor. He strengthens gentle faithfulness and meets you in the hidden work of love.',
                'reflection' => 'Where do I need God to shepherd me as I care for others?',
                'prayer' => 'Good Shepherd, give me patience, wisdom, and strength for the people entrusted to my care.',
                'declaration' => 'God supplies grace for the people and responsibilities He has entrusted to me.',
            ],
            [
                'category' => 'Work and Calling',
                'title' => 'Serving God Through Your Work',
                'reference' => 'Colossians 3:23',
                'verse' => 'And whatsoever ye do, do it heartily, as to the Lord, and not unto men.',
                'event' => 'career, business, school, ministry, leadership, job dissatisfaction, or the desire for meaningful work',
                'truth' => 'Work becomes worship when it is offered to God with integrity, excellence, service, and humility.',
                'practice' => 'Invite God into your work before you begin. Ask Him to purify your motives, sharpen your skill, and make your labor a blessing.',
                'discipline' => 'Choose one task today and do it as worship: without complaint, without shortcuts, and without needing applause.',
                'warning' => 'Do not let ambition disciple your heart more than Christ. Success without surrender can quietly become bondage.',
                'hope' => 'God uses ordinary work to form character, serve people, and open doors that align with His purpose.',
                'reflection' => 'How can my work become more faithful, excellent, and surrendered to God?',
                'prayer' => 'Lord, receive my work as worship and make my labor fruitful for Your glory.',
                'declaration' => 'My work belongs to the Lord.',
            ],
            [
                'category' => 'Work and Calling',
                'title' => 'When You Feel Unseen in Your Assignment',
                'reference' => 'Hebrews 6:10',
                'verse' => 'For God is not unrighteous to forget your work and labour of love.',
                'event' => 'hidden service, delayed promotion, overlooked effort, ministry fatigue, or quiet obedience without recognition',
                'truth' => 'Being unseen by people does not mean being unseen by God. Heaven keeps better records than human applause.',
                'practice' => 'Serve from sonship, not performance. Let the Father be enough witness for the obedience He assigned.',
                'discipline' => 'Do one hidden act of faithfulness today without mentioning it, and offer it to God in prayer.',
                'warning' => 'Do not let lack of recognition corrupt the purity of your service. Bitterness can steal the reward of hidden faithfulness.',
                'hope' => 'God knows how to honor what was done in love, even when people missed it.',
                'reflection' => 'Where have I allowed being overlooked to weaken my obedience?',
                'prayer' => 'Father, purify my motives and strengthen me to serve faithfully before You.',
                'declaration' => 'God sees my labor of love and remembers my obedience.',
            ],
            [
                'category' => 'Money and Stewardship',
                'title' => 'Trusting God With Your Finances',
                'reference' => 'Matthew 6:33',
                'verse' => 'But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.',
                'event' => 'financial pressure, debt, job loss, budgeting, giving, business decisions, or fear about provision',
                'truth' => 'God cares about your needs, but He also cares about the order of your loves. Provision is not only about money; it is about trust, wisdom, and kingdom priority.',
                'practice' => 'Bring your finances into the light of prayer. Ask God for provision, discipline, contentment, generosity, and honest stewardship.',
                'discipline' => 'Review your spending with God: identify one waste to reduce, one debt step to take, and one way to practice generosity.',
                'warning' => 'Do not let fear make you dishonest, impulsive, or closed-hearted. Pressure is real, but panic is not a financial plan.',
                'hope' => 'The Father who feeds birds and clothes fields can guide your practical steps and sustain your needs.',
                'reflection' => 'What would seeking the kingdom first look like in my finances this week?',
                'prayer' => 'Provider, teach me wisdom, contentment, generosity, and trust in every financial season.',
                'declaration' => 'I seek Gods kingdom first and trust Him with my needs.',
            ],
            [
                'category' => 'Money and Stewardship',
                'title' => 'Freedom From the Fear of Lack',
                'reference' => 'Psalm 23:1',
                'verse' => 'The LORD is my shepherd; I shall not want.',
                'event' => 'scarcity, unemployment, business uncertainty, rising expenses, or fear that there will not be enough',
                'truth' => 'The Shepherd does not promise a life without valleys, but He promises His presence, provision, guidance, and care inside them.',
                'practice' => 'Declare Gods shepherding over your needs, then take practical steps with wisdom: ask for counsel, make a plan, work diligently, and refuse despair.',
                'discipline' => 'Each morning this week, pray Psalm 23 slowly and write one practical obedience for the day.',
                'warning' => 'Do not let lack define God for you. Circumstances can describe a season, but they cannot describe His character.',
                'hope' => 'You may not see the whole supply yet, but you are not shepherdless.',
                'reflection' => 'Where has fear of lack been shaping my decisions more than trust in God?',
                'prayer' => 'Lord my Shepherd, lead me in wise provision and free me from fear.',
                'declaration' => 'The Lord is my Shepherd; I am not abandoned in need.',
            ],
            [
                'category' => 'Health and Healing',
                'title' => 'Faith When Your Body Is Weak',
                'reference' => '2 Corinthians 12:9',
                'verse' => 'My grace is sufficient for thee: for my strength is made perfect in weakness.',
                'event' => 'sickness, chronic pain, recovery, fatigue, caregiving, diagnosis, or physical limitation',
                'truth' => 'Weakness does not disqualify you from Gods love or usefulness. Grace can meet you in a body that feels fragile.',
                'practice' => 'Pray honestly for healing and also for grace today. Receive medical wisdom without shame, ask for help without pride, and let weakness become a place of dependence.',
                'discipline' => 'Choose one gentle act of stewardship for your body today: rest, hydration, medication, a walk, a doctor appointment, or asking for support.',
                'warning' => 'Do not measure your faith only by how strong you feel. Sometimes faith looks like clinging to God from a place of weakness.',
                'hope' => 'The strength of Christ is not embarrassed by your limits. His grace is sufficient here.',
                'reflection' => 'How can I honor God with both faith for healing and wise care for my body?',
                'prayer' => 'Jesus, meet me in weakness with healing, patience, and sufficient grace.',
                'declaration' => 'The grace of Christ is sufficient for me today.',
            ],
            [
                'category' => 'Health and Healing',
                'title' => 'Hope During Recovery',
                'reference' => 'Jeremiah 30:17',
                'verse' => 'For I will restore health unto thee, and I will heal thee of thy wounds, saith the LORD.',
                'event' => 'recovery after illness, emotional healing, therapy, rehabilitation, surgery, trauma, or a slow return to strength',
                'truth' => 'Restoration is often a process, not a single moment. God is present in small improvements, patient endurance, and hidden repair.',
                'practice' => 'Celebrate small signs of grace. A little strength, a clearer thought, a peaceful hour, or a courageous conversation can be evidence of restoration.',
                'discipline' => 'Keep a recovery gratitude list for seven days, naming one mercy each day that you might otherwise overlook.',
                'warning' => 'Do not despise slow healing. Impatience can make you miss the quiet ways God is rebuilding you.',
                'hope' => 'The Lord knows how to restore what has been wounded, and He is not rushed by the pace that frustrates you.',
                'reflection' => 'What small sign of restoration can I thank God for today?',
                'prayer' => 'Lord, restore my health, heal my wounds, and give me patience for the process.',
                'declaration' => 'God is working restoration in me, step by step.',
            ],
            [
                'category' => 'Waiting and Discernment',
                'title' => 'When the Answer Has Not Come Yet',
                'reference' => 'Psalm 27:14',
                'verse' => 'Wait on the LORD: be of good courage, and he shall strengthen thine heart.',
                'event' => 'delayed prayer, waiting for marriage, employment, healing, direction, children, breakthrough, or clarity',
                'truth' => 'Waiting is not wasted when it is surrendered to God. The Lord strengthens the heart that refuses to abandon trust.',
                'practice' => 'Wait actively, not passively. Pray, prepare, obey what is already clear, and refuse the shortcuts that require disobedience.',
                'discipline' => 'Make two lists: what you are waiting for, and what God has already told you to do while you wait.',
                'warning' => 'Do not let delay make you reckless. Ishmael decisions often come from refusing the pain of waiting.',
                'hope' => 'God can strengthen you before He changes the circumstance. The waiting room can become a training room.',
                'reflection' => 'What obedience is available to me while I wait for the answer I want?',
                'prayer' => 'Lord, strengthen my heart and keep me faithful while I wait.',
                'declaration' => 'I wait on the Lord with courage and obedience.',
            ],
            [
                'category' => 'Waiting and Discernment',
                'title' => 'Wisdom for Big Decisions',
                'reference' => 'James 1:5',
                'verse' => 'If any of you lack wisdom, let him ask of God, that giveth to all men liberally.',
                'event' => 'choosing a spouse, job, school, church, city, investment, ministry path, or life direction',
                'truth' => 'God is generous with wisdom. He is not annoyed by sincere questions, but He does call you to ask with humility and obey with integrity.',
                'practice' => 'Bring the decision under Scripture, prayer, counsel, timing, motives, and peace. Do not isolate one sign and ignore the whole witness of wisdom.',
                'discipline' => 'Write the decision plainly, then evaluate it through five questions: Is it biblical? Is it wise? Is it honest? Is it loving? Is it timely?',
                'warning' => 'Do not baptize impulse as faith. Faith can move boldly, but it does not need to ignore wisdom.',
                'hope' => 'The God who gives wisdom can guide both your heart and your steps.',
                'reflection' => 'What part of this decision needs more prayer, counsel, or patience?',
                'prayer' => 'God of wisdom, guide my motives, thoughts, timing, and next steps.',
                'declaration' => 'God gives me wisdom generously as I ask in faith.',
            ],
            [
                'category' => 'Failure and Restoration',
                'title' => 'After You Have Fallen',
                'reference' => 'Proverbs 24:16',
                'verse' => 'For a just man falleth seven times, and riseth up again.',
                'event' => 'sin, relapse, moral failure, broken promises, inconsistency, or returning to God after drifting',
                'truth' => 'Falling is serious, but it is not final when grace calls you to rise. The righteous life is not marked by never needing mercy; it is marked by returning to God.',
                'practice' => 'Confess specifically, receive forgiveness, remove access to the pattern, and invite accountability that helps you walk in the light.',
                'discipline' => 'Take one concrete repentance step today: delete, confess, apologize, schedule counsel, change a habit, or ask for prayer.',
                'warning' => 'Do not make peace with what wounded your soul. Grace is not permission to stay bound; grace is power to rise.',
                'hope' => 'God restores people who come honestly. Your fall does not have to become your future.',
                'reflection' => 'What practical step of repentance must I take now, not later?',
                'prayer' => 'Father, forgive me, cleanse me, and teach me to rise in obedience.',
                'declaration' => 'By the grace of God, I rise again and walk in the light.',
            ],
            [
                'category' => 'Failure and Restoration',
                'title' => 'When Regret Keeps Speaking',
                'reference' => 'Romans 8:1',
                'verse' => 'There is therefore now no condemnation to them which are in Christ Jesus.',
                'event' => 'regret over past decisions, shame, missed opportunities, old sin, or memories that accuse you',
                'truth' => 'Conviction leads you to God. Condemnation drives you away. Learn the voice of grace so regret does not become your shepherd.',
                'practice' => 'When regret speaks, answer with truth. If restitution is needed, make it. If confession is needed, give it. If forgiveness has been received, stand in it.',
                'discipline' => 'Write Romans 8:1 and place it where you will see it. Read it aloud when accusation returns.',
                'warning' => 'Do not let the enemy use your past to steal todays obedience. Shame wants you frozen; grace calls you forward.',
                'hope' => 'In Christ, your past can become testimony, wisdom, humility, and compassion instead of a prison.',
                'reflection' => 'Is what I am hearing conviction that leads to obedience, or condemnation that leads to hiding?',
                'prayer' => 'Jesus, silence condemnation and lead me in the freedom of Your grace.',
                'declaration' => 'There is no condemnation for me in Christ Jesus.',
            ],
            [
                'category' => 'Spiritual Growth',
                'title' => 'Learning to Pray Every Day',
                'reference' => 'Luke 11:1',
                'verse' => 'Lord, teach us to pray.',
                'event' => 'building a prayer life, feeling spiritually dry, wanting consistency, or not knowing what to say to God',
                'truth' => 'Prayer is learned in relationship. You grow by coming, speaking honestly, listening patiently, and returning again.',
                'practice' => 'Start simple and sincere. Praise God for who He is, confess what needs cleansing, ask for daily bread, surrender your will, and listen quietly.',
                'discipline' => 'Set a small daily prayer appointment for the next seven days. Keep it short enough to obey and sacred enough to honor.',
                'warning' => 'Do not wait until prayer feels impressive. Consistency often grows from small, faithful beginnings.',
                'hope' => 'The Spirit helps weak prayers. God is not measuring eloquence; He is forming communion.',
                'reflection' => 'What simple daily prayer rhythm can I actually keep this week?',
                'prayer' => 'Lord, teach me to pray with honesty, faith, and consistency.',
                'declaration' => 'My prayer life is growing through daily communion with God.',
            ],
            [
                'category' => 'Spiritual Growth',
                'title' => 'How Scripture Changes You',
                'reference' => 'Psalm 119:105',
                'verse' => 'Thy word is a lamp unto my feet, and a light unto my path.',
                'event' => 'wanting to understand the Bible, needing direction, growing in holiness, or building spiritual discipline',
                'truth' => 'Scripture is not only information. It is light, correction, nourishment, warning, comfort, and a meeting place with God.',
                'practice' => 'Read slowly enough to respond. Ask what the passage reveals about God, what it exposes in you, and what obedience it invites.',
                'discipline' => 'Choose one chapter this week. Read it daily, write one sentence of insight, and practice one command or truth.',
                'warning' => 'Do not read only to collect knowledge. Knowledge without obedience can make the heart proud but unchanged.',
                'hope' => 'The Word of God can light the next step even when the whole road is not visible.',
                'reflection' => 'What Scripture have I understood but not yet obeyed?',
                'prayer' => 'Lord, open my heart to Your Word and make me obedient to Your light.',
                'declaration' => 'Gods Word is a lamp to my feet and a light to my path.',
            ],
            [
                'category' => 'Spiritual Growth',
                'title' => 'Growing When You Feel Spiritually Dry',
                'reference' => 'John 7:38',
                'verse' => 'He that believeth on me, as the scripture hath said, out of his belly shall flow rivers of living water.',
                'event' => 'dry prayer, dull worship, lack of desire, spiritual fatigue, or feeling distant from God',
                'truth' => 'Dryness is not always abandonment. Sometimes it is an invitation to deeper thirst, simpler obedience, and renewed dependence.',
                'practice' => 'Return to the basics without drama: confess sin, read Scripture, pray honestly, worship quietly, gather with believers, and serve someone in love.',
                'discipline' => 'For three days, pray one sentence every hour: "Jesus, renew my thirst for You."',
                'warning' => 'Do not feed dryness with isolation, hidden sin, constant distraction, or comparison.',
                'hope' => 'The living water of Christ can flow again in places that feel barren.',
                'reflection' => 'What habit or distraction may be making my soul more dry?',
                'prayer' => 'Jesus, renew my thirst and let Your living water flow in me again.',
                'declaration' => 'My soul is renewed by the living water of Christ.',
            ],
            [
                'category' => 'Courage and Resilience',
                'title' => 'Courage When You Feel Alone',
                'reference' => 'Deuteronomy 31:6',
                'verse' => 'Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee.',
                'event' => 'loneliness, rejection, relocation, standing for truth, leadership pressure, or feeling unsupported',
                'truth' => 'Loneliness is real, but it is not the final truth about your life. The Lord goes with you even when people do not understand the road.',
                'practice' => 'Name the loneliness honestly, then anchor yourself in Gods presence. Reach for healthy community without making people responsible to be God.',
                'discipline' => 'Send one honest message to a trusted person, and spend ten minutes in prayer receiving the nearness of God.',
                'warning' => 'Do not let loneliness push you toward unhealthy attachment, compromise, or bitterness.',
                'hope' => 'God can strengthen you in hidden places and connect you to people who help you walk wisely.',
                'reflection' => 'Where do I need to receive Gods presence instead of letting loneliness lead me?',
                'prayer' => 'Lord, strengthen me with Your presence and lead me into healthy community.',
                'declaration' => 'I am not abandoned; the Lord my God goes with me.',
            ],
            [
                'category' => 'Courage and Resilience',
                'title' => 'Standing Firm Under Pressure',
                'reference' => '1 Corinthians 16:13',
                'verse' => 'Watch ye, stand fast in the faith, quit you like men, be strong.',
                'event' => 'temptation, persecution, workplace pressure, peer pressure, cultural pressure, or costly obedience',
                'truth' => 'Courage is not loudness. Courage is steady obedience when compromise would be easier.',
                'practice' => 'Decide your convictions before the pressure peaks. Pray for strength, prepare your words, and keep your spirit free from arrogance.',
                'discipline' => 'Write one conviction you must not compromise, and identify one support person who can pray with you.',
                'warning' => 'Do not confuse stubborn pride with spiritual courage. True courage remains humble, watchful, and submitted to God.',
                'hope' => 'The Spirit of God can make you firm without making you hard.',
                'reflection' => 'Where is God asking me to stand firm with humility and courage?',
                'prayer' => 'Lord, make me watchful, faithful, humble, and strong under pressure.',
                'declaration' => 'By Gods grace, I stand firm in the faith.',
            ],
            [
                'category' => 'Relationships',
                'title' => 'Wisdom for Singleness',
                'reference' => 'Psalm 16:11',
                'verse' => 'Thou wilt shew me the path of life: in thy presence is fulness of joy.',
                'event' => 'singleness, waiting for marriage, healing from past relationships, loneliness, or discovering purpose before partnership',
                'truth' => 'Singleness is not a waiting room for significance. Your life is already valuable, fruitful, and called before God.',
                'practice' => 'Let this season be formed by presence, purpose, community, purity, and growth. Desire marriage honestly without surrendering joy to its delay.',
                'discipline' => 'Invest in one area of growth this month: spiritual discipline, emotional healing, financial wisdom, service, or friendship.',
                'warning' => 'Do not trade peace for attention. A relationship that pulls you from God is too expensive.',
                'hope' => 'The fullness of joy is found first in Gods presence, and from that place you can love without desperation.',
                'reflection' => 'How can I live this season fully instead of treating it as incomplete?',
                'prayer' => 'Lord, fill my life with Your presence, purpose, purity, and joy.',
                'declaration' => 'My life is fruitful and beloved in every season.',
            ],
            [
                'category' => 'Relationships',
                'title' => 'Marriage as Daily Covenant',
                'reference' => 'Ecclesiastes 4:12',
                'verse' => 'A threefold cord is not quickly broken.',
                'event' => 'marriage, engagement, conflict, rebuilding trust, communication struggles, or learning covenant love',
                'truth' => 'Marriage is strengthened when both hearts keep returning to God. Covenant is not sustained by feelings alone, but by humility, repentance, service, and prayer.',
                'practice' => 'Invite God into the daily places where marriages often drift: tone, time, money, intimacy, forgiveness, and expectations.',
                'discipline' => 'Have one honest conversation this week that begins with humility, not accusation.',
                'warning' => 'Do not let pride become a roommate in your home. Pride turns small issues into walls.',
                'hope' => 'God can strengthen the cord when both people are willing to be formed by Him.',
                'reflection' => 'What act of humility could strengthen love in my marriage or future marriage?',
                'prayer' => 'Lord, teach me covenant love that is patient, truthful, humble, and faithful.',
                'declaration' => 'God forms my love into covenant faithfulness.',
            ],
            [
                'category' => 'New Seasons',
                'title' => 'Graduation and the Courage to Begin',
                'reference' => 'Proverbs 3:5-6',
                'verse' => 'Trust in the LORD with all thine heart; and lean not unto thine own understanding.',
                'event' => 'graduation, finishing school, entering adulthood, beginning work, changing identity, or stepping into responsibility',
                'truth' => 'A completed season is a gift, but it is not your god. The Lord who helped you finish will also guide you as you begin.',
                'practice' => 'Commit your plans to God before you chase speed. Ask for wisdom, mentors, discipline, and a heart that values character over image.',
                'discipline' => 'Write a personal rule of life for the next season: prayer, work, money, friendship, church, rest, and service.',
                'warning' => 'Do not let achievement replace dependence. Success can become dangerous when it makes prayer feel optional.',
                'hope' => 'God is able to direct paths that feel larger than your experience.',
                'reflection' => 'What kind of person do I want to become as I enter this next responsibility?',
                'prayer' => 'Lord, direct my path and form my character as I begin this new season.',
                'declaration' => 'I trust the Lord with my future and my formation.',
            ],
            [
                'category' => 'Family and Home',
                'title' => 'Healing From Family Wounds',
                'reference' => 'Psalm 147:3',
                'verse' => 'He healeth the broken in heart, and bindeth up their wounds.',
                'event' => 'family rejection, parental wounds, sibling conflict, childhood pain, generational patterns, or complicated holidays',
                'truth' => 'Family wounds can go deep, but they are not beyond the reach of God. The Lord binds what people broke and teaches you a new way to live.',
                'practice' => 'Let healing include truth. Name what happened, grieve what was missing, forgive as God leads, and learn patterns that do not repeat the wound.',
                'discipline' => 'Identify one family pattern you will not carry forward, and one godly practice you will intentionally build.',
                'warning' => 'Do not confuse honoring family with enabling harm. Honor can include boundaries, truth, and prayer from a wise distance.',
                'hope' => 'God can make you a beginning of blessing, even if you came from a line of pain.',
                'reflection' => 'What wound needs Gods healing, and what pattern needs to stop with me?',
                'prayer' => 'Lord, heal my family wounds and make me a vessel of generational blessing.',
                'declaration' => 'God heals my heart and teaches me a new way to live.',
            ],
            [
                'category' => 'Work and Calling',
                'title' => 'When Business Feels Heavy',
                'reference' => 'Psalm 90:17',
                'verse' => 'And let the beauty of the LORD our God be upon us: and establish thou the work of our hands upon us.',
                'event' => 'entrepreneurship, business pressure, leadership fatigue, uncertain sales, staff responsibility, or carrying vision',
                'truth' => 'God cares about work that serves people with integrity. Business can be a place of worship when it is surrendered, honest, diligent, and generous.',
                'practice' => 'Pray over decisions, customers, staff, numbers, strategy, and motives. Ask God to establish what is righteous and expose what is unhealthy.',
                'discipline' => 'Review one business decision through the lens of integrity, service, sustainability, and prayer.',
                'warning' => 'Do not sacrifice your soul, family, or integrity on the altar of growth.',
                'hope' => 'The Lord can establish the work of your hands and teach you to build without bondage.',
                'reflection' => 'Where does my work or business need deeper surrender to God?',
                'prayer' => 'Lord, establish the work of my hands and keep my heart faithful.',
                'declaration' => 'My work is surrendered to God, built with wisdom, and used for good.',
            ],
            [
                'category' => 'Courage and Resilience',
                'title' => 'Faith During a Crisis',
                'reference' => 'Psalm 46:1',
                'verse' => 'God is our refuge and strength, a very present help in trouble.',
                'event' => 'emergency, bad news, family crisis, sudden loss, danger, or a moment when life changes quickly',
                'truth' => 'Crisis can shake your surroundings, but it does not remove Gods nearness. He is not only help after trouble; He is present in trouble.',
                'practice' => 'Stabilize your soul before making every decision. Pray, breathe, call wise support, handle the next urgent step, and return to prayer again.',
                'discipline' => 'Use a crisis prayer: "God, be my refuge. Give me wisdom for the next right step." Repeat it whenever panic rises.',
                'warning' => 'Do not let fear force every decision into urgency. Some moments require quick action; others require quiet wisdom.',
                'hope' => 'God can be refuge while the storm is still loud.',
                'reflection' => 'What is the next right step I can take with God as my refuge?',
                'prayer' => 'God, be my refuge, strength, wisdom, and help in this trouble.',
                'declaration' => 'God is my present help in trouble.',
            ],
        ];
    }

    /**
     * @param  array<string, string>  $post
     */
    private function buildContent(array $post): string
    {
        return implode("\n\n", [
            "Life event: {$post['event']}. This devotional is for the moments when ordinary advice is not enough and your soul needs to be anchored again in the presence of God.",
            "Spiritual truth: {$post['truth']} The Lord does not ask you to pretend that life is easy. He invites you to bring the whole truth of your season into communion with Him, where fear is corrected, desire is purified, pain is held, and obedience becomes possible.",
            "How to walk it out: {$post['practice']} Do not rush past the inner work. God often forms people in the hidden places before He changes the visible circumstances. Let prayer become the first response, Scripture the loudest voice, humility the posture, and obedience the next step.",
            "Practice for today: {$post['discipline']} Keep the practice simple enough to obey today, but meaningful enough to shape tomorrow. Spiritual growth usually happens through repeated surrender, not dramatic intention alone.",
            "Wisdom guardrail: {$post['warning']} A life event can expose what has been ruling the heart. Let this season reveal what needs healing, repentance, counsel, rest, courage, or deeper trust. Refuse every shortcut that requires you to disobey God to feel safe.",
            "Hope in Christ: {$post['hope']} You are not alone in this moment. The Father sees you, the Son intercedes for you, and the Spirit strengthens you. Take the next faithful step, and trust God with the parts you cannot control.",
        ]);
    }
}
